name: Post to Livedoor Blog

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install markdown-it
          npm install openai

      - name: Run AtomPub post
        env:
          LD_USER: ${{ secrets.LD_USER }}
          LD_ATOM_PASS: ${{ secrets.LD_ATOM_PASS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          POST_TITLE: "AI自動投稿テスト"
        run: node atompub-post.js
